### ISSUE TITLE
Overture Playground Dataset 

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/dms#167]
### Overture Playground Dataset

Outline and organize a representative open-access mock data set to include with the DMS. 

- Metadata fields should be representative of a Cancer genomics research group(s)
- Should allow us to show all arranger faceted search options (quick search, radial filters, date range)
- Must comply with [Songs base schema and base meta schema](https://www.overture.bio/documentation/song/admin/schemas/)
- For demo purposes, the metadata should consider Song functionalities, including analysis types required (separate ticket) and publication states (Most data will be published, but we should consider including some unpublished and some suppressed)
<br></br>
- File data should be as big as necessary (the smaller, the better)
- File data should support all Jbrowse functionalities (VCFs, BAMs, BCFs, BEDs, etc.)
- To show arrangers pagination, we are looking for ~550 records; however, we do not need unique file data for all ~550 records
- For demo purposes, the file data should also consider Score functionalities (BAM/CRAM slicing, etc.)

**Metadata Tasks**
- [x] **Outline required metadata fields**
- [x] **Review Outline**
- [x] **Produce Song Schema**
- [x] **Generate metadata payloads**
- [x] **Review Schema + Update google sheet (Mitchell)**

**File Data Tasks**
- [x] **Outline required file data**
- [x] **Review Outline**
- [x] **Organize/generate file data (Synthetic VFCs + Links to open access file data)**

**General Tasks**
- [x] **Song Schemas, metadata payloads and dummy file data with links to open access file data placed in a folder within the DMS repo link to the [relevant PR](https://github.com/overture-stack/dms/pull/165
)**

## Links 

[Co-ordination doc](https://wiki.oicr.on.ca/display/OV/DMS+Playground+Data+Co-Ordination)
[Song Metadata Fields](https://docs.google.com/spreadsheets/d/1rqbXtmL8ZImzGxZxdgtlPUB0v5pqUn7x_fAKyXS4D2c/edit#gid=76350143)
[Base Schema Updates](https://wiki.oicr.on.ca/display/OV/Song+schemas+update)
[Link to issue](https://github.com/overture-stack/dms/issues/167)

**Comment by justincorrigible** [comment]
Almost done generating the corresponding Elasticsearch mapping to match the schema created in this ticket.
Noticed a couple items that needed clarification and we may want to adjust here:

- `samples.donor` vs `donor`. is this a duplicate property?
Resolution: yes, but the `samples.donor` comes from the song base schema, and we cannot remove it right now. https://www.overture.bio/documentation/song/admin/schemas/#the-song-base-schema

- `tumour` (British) vs `tumor` (Atlantic) ?
Resolution: keeping `tumour` because of base schema limitations.

- Archives'`fileID` vs file/object ids? (`archive.ENCODE.fileID` could be a specific property name + spelling)
Resolution: @edsu7 to confirm property names for each archive.

- `followup` vs `follow_up`: consistent spacing/punctuation for `donor.primary_diagnosis.follow_up`, and its properties.
Resolution: we're option for a consistent `follow_up`. **Not needed will be camel-cased `followUp`
  - [x] Mapping updated
  - [x] Schema updated
  - [x] Analyses updated

- update `collaborator` to `collaborator(s)`
  - [x] Mapping updated
  - [x] Schema updated
  - [x] Analyses updated

- `center` vs `centre`. e.g. `experiment.sequencing_center`. this property is spelled in Atlantic, which is not consistent.
Resolution: changing to centre, for consistency with British spelling, and base schema limitations.
  - [x] Mapping updated
  - [x] Schema updated
  - [x]  Analyses updated

- `specimen.cell_line.treatment.treatment_typed`. extra “d” in property name, at the end
Resolution: Remove the typo.
  - [x] Mapping updated
  - [x] Schema updated
  - [x] Analyses updated

-  camelCasing: The base schema is in camelCase, and we should keep things consistent in the whole schema.
Resolution: we're unifying to camelCase wherever possible
  - [x] Mapping updated
  - [x] Schema updated
  - [x] Analyses updated
